Fix broken variable resolution with ${certificate:name:CertificateArn…
schwamster/serverless-certificate-creator pull request #32
Opened 2021-02-25 21:49 UTC by williamsandonz

2.27.0's has introduced the new variable resolver which will become the future default. Users on 2.27.0 can now elect to use the new resolver by adding variablesResolutionMode: 20210219 to the root of their serverless.yml. If they do this, `${certificate:${self:custom.customCertificate.certificateName}:CertificateArn}`. will cause a compilation failure because using ':' more than once is now illegal. The new syntax uses a '.' in place of this. I've added conditional logic to getCertificateProperty to resolve path when new resolver is being used.

2021-02-27 10:40 UTC, williamsandonz commented
Hey @schwamster, sorry to bother you but can I request a review on this ? It's causing issues on my plugin https://www.npmjs.com/package/serverless-website-domain. Cheers!

2021-02-27 13:02 UTC, baconbeaast approved these changes

2021-02-27 15:23 UTC, schwamster approved these changes

2021-02-27 15:46 UTC, schwamster requested changes
I just tested this and it failed:

  TypeError: Cannot read property 'variablesResolutionMode' of undefined
      at CreateCertificatePlugin.getCertificateProperty (C:\git\serverless-certificate-creator\index.js:486:44)

this.serverless.configurationInput does not exist.

The code does not seem to be backward compatible. Can you take a look?

2021-02-27 16:16 UTC, williamsandonz commented
@schwamster Good catch, thanks. I've wrapped it up in a try catch so should handle any failures now, not the most elegant but should be fit for purpose. From what I can see configurationInput seems to be the correct property to use but just doesn't exist in older versions.

2021-02-27 22:35 UTC, schwamster commented
thanks @williamsandonz ! I made some more changes and released version 1.5.0 -> https://github.com/schwamster/serverless-certificate-creator/releases/tag/v1.5.0

Hope that helps

2021-02-27 22:35 UTC, closed without merging

2021-02-28 09:32 UTC, williamsandonz commented
@schwamster  Legend! Thanks again :)